#!/bin/bash

# Usage: ./generate_map_sizes.sh <ldtk_file> [output_file]
# Example: ./generate_map_sizes.sh ./ldtk/genesis_level_2.ldtk ./inc/map_sizes.h

LDTK_FILE="${1:-./ ldtk/genesis_level_2.ldtk}"
OUTPUT_FILE="${2:-./ inc/map_sizes.h}"

if [ ! -f "$LDTK_FILE" ]; then
    echo "Error: ldtk file not found: $LDTK_FILE"
    exit 1
fi

# Generate the header file with level map sizes
{
    echo "#ifndef MAP_SIZES_H"
    echo "#define MAP_SIZES_H"
    echo ""
    echo "#include \"xtypes.h\""
    echo ""
    echo "// Auto-generated map sizes from ldtk file"
    echo "// Generated by generate_map_sizes.sh"
    echo ""
    
    # Count levels to determine array size
    LEVEL_COUNT=$(jq '.levels | length' "$LDTK_FILE")
    
    echo "const Vect2D_u16 mapSizes[$LEVEL_COUNT] = {"
    
    # Extract pxWid and pxHei from each level and format as Vect2D_u16 initializers
    jq -r '.levels[:-1][] | "    {" + (.pxWid | tostring) + ", " + (.pxHei | tostring) + "},"' "$LDTK_FILE"
    
    # Last element without comma
    jq -r '.levels[-1] | "    {" + (.pxWid | tostring) + ", " + (.pxHei | tostring) + "}"' "$LDTK_FILE"
    
    echo "};"
    echo ""
    echo "#define NUM_LEVELS $LEVEL_COUNT"
    echo ""
    echo "#endif // MAP_SIZES_H"
    
} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE with $LEVEL_COUNT levels"
