#ifndef MAP_SIZES_H
#define MAP_SIZES_H

#include "xtypes.h"

// Auto-generated map sizes from ldtk file
// Generated by generate_map_sizes.sh

const Vect2D_u16 mapSizes[2] = {
    {768, 256},
    {512, 512}
};

#define NUM_LEVELS 2

#endif // MAP_SIZES_H
